variables:
  DEPLOY_VARIABLE: "default-deploy"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        DEPLOY_VARIABLE: "deploy-production"  # Override globally-defined DEPLOY_VARIABLE
    - if: $CI_COMMIT_REF_NAME =~ /feature/
      variables:
        IS_A_FEATURE: "true"                  # Define a new variable.
    - when: always  

job:
  script: echo "$CI_COMMIT_REF_NAME vs $CI_COMMIT_BRANCH"
  rules:
    - if: $CI_COMMIT_REF_NAME =~ main
      when: never