variables:
  DEPLOY_VARIABLE: "default-deploy"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        DEPLOY_VARIABLE: "deploy-production"  # Override globally-defined DEPLOY_VARIABLE
    - if: $CI_COMMIT_REF_NAME =~ /feature/
      variables:
        IS_A_FEATURE: "true"                  # Define a new variable.
    - when: always  

job:
  script: echo "Hello, Rules!"
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^feature/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^feature/
      when: manual
      allow_failure: true
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME

job1:
  script:
    - echo "Run script with $DEPLOY_VARIABLE as an argument"
    - echo "$CI_COMMIT_REF_NAME vs $CI_COMMIT_BRANCH"
    - echo "Run another script if $IS_A_FEATURE exists"
  rules:
    - if: $CI_COMMIT_REF_NAME != release
      when: never

job2:
  script:
    - echo "Run script with $DEPLOY_VARIABLE as an argument"
    - echo "$CI_COMMIT_REF_NAME vs $CI_COMMIT_BRANCH"
    - echo "Run another script if $IS_A_FEATURE exists"
  rules:
    - if: '"$CI_COMMIT_BRANCH" =~ main'  