---
deploy-dev:
  script: bash ./test.sh
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^develop$/'

deploy-stg:
  script: bash ./test.sh
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release\/v[0-9]+(?:.[0-9]+)+$/'

deploy-prd:
  script: bash ./test.sh
  rules:
    - if: $CI_COMMIT_TAG