---
variables:
  DEBUG_ENABLE: "" # debug disabled

deploy-dev:
  script: bash ./script.sh
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^develop$/'

deploy-stg:
  script: bash ./script.sh
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release\/v[0-9]+(?:.[0-9]+)+$/'

deploy-prd:
  script: bash ./script.sh
  rules:
    - if: $CI_COMMIT_TAG